### ISSUE TITLE
pip installer errors

### ISSUE THREAD

**Issue by PaulMelloy** [PaulMelloy/meeting_summary#1]
on development of this package I had some errors from pip installer

I worked around this by installing packages in a virtual environment

```sh
# install the virtual environment package
sudo apt install python3.12-venv

# create a virtual environment called 'myenv'
python3 -m venv myenv

# activate the venv
source myenv/bin/activate

# install python packages
pip install vttformatter
pip install webvtt-py
```

**Comment by la-w8** [comment]
![image](https://github.com/user-attachments/assets/9bda67dc-85c9-4a3a-8f6e-a25c7933f6b0)

**Comment by la-w8** [comment]
I have a beef with pip

**Comment by PaulMelloy** [comment]
I found a much simpler work around and updated the README so the vtt file converter  is not needed see 56381924ba32c2006e68c7525e2e755a6461a58e

**Comment by la-w8** [comment]
> I found a much simpler work around and updated the README so the vtt file converter  is not needed see 56381924ba32c2006e68c7525e2e755a6461a58e

thx
